// settings for front end
// export const API_URL = "http://localhost:5005/";
export const API_URL = "/";
export const allowedTitleChars = 105;
export const MAX_PRODUCT_PRICE = 10000000;
export const pubKey = 'BK35z7AqYNsM8GoWa-i3kie9hDuRV38LV6X0IzQqVEeE4304BXLIe8c2ywAunRDQFmJhMwfsJCil71Fpd_5VbrA';
export const adsPerPage = 10;

// USER ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

// AD ACTIONS
export const SUBMIT_AD = "SUBMIT_AD";
export const SUBMIT_AD_SUCCESS = "SUBMIT_AD_SUCCESS";
export const UPDATE_AD = "UPDATE_AD";
export const UPDATE_AD_SUCCESS = "UPDATE_AD_SUCCESS";
export const SEARCH_ADS = "SEARCH_ADS";
export const SEARCH_ADS_SUCCESS = "SEARCH_ADS_SUCCESS";
export const FILTER_ADS = "FILTER_ADS";
export const FILTER_ADS_SUCCESS = "FILTER_ADS_SUCCESS";
export const LOAD_ALL_ADS = "LOAD_ALL_ADS";
export const LOAD_ALL_ADS_SUCCESS = "LOAD_ALL_ADS_SUCCESS";
export const LOAD_MY_ADS = "LOAD_MY_ADS";
export const LOAD_MY_ADS_SUCCESS = "LOAD_MY_ADS_SUCCESS";
export const DELETE_AD = "DELETE_AD";
export const DELETE_AD_SUCCESS = "DELETE_AD_SUCCESS";
export const LOAD_CATEGORIES_COUNTS = "LOAD_CATEGORIES_COUNTS";
export const LOAD_CATEGORIES_COUNTS_SUCCESS = "LOAD_CATEGORIES_COUNTS_SUCCESS";
export const LOAD_SAVED_ADS = "LOAD_SAVED_ADS";
export const LOAD_SAVED_ADS_SUCCESS = "LOAD_SAVED_ADS_SUCCESS";
export const REMOVE_SAVED_AD = "REMOVE_SAVED_AD";

export const AD_VIEW_LATER = "AD_VIEW_LATER";
export const AD_VIEW_LATER_SUCCESS = "AD_VIEW_LATER_SUCCESS";
export const SAVE_AD_IN_CACHE = "SAVE_AD_IN_CACHE";
export const SAVE_AD_IN_CACHE_SUCCESS = "SAVE_AD_IN_CACHE_SUCCESS";
export const GET_ALL_ADS_COUNT = "GET_ALL_ADS_COUNT";
export const GET_ALL_ADS_COUNT_SUCCESS = "GET_ALL_ADS_COUNT_SUCCESS";

export const REQUEST_NOTIFICATION_PERMISSION = "REQUEST_NOTIFICATION_PERMISSION";
export const REQUEST_NOTIFICATION_PERMISSION_GRANTED = "REQUEST_NOTIFICATION_PERMISSION_GRANTED";
export const REQUEST_NOTIFICATION_PERMISSION_DENIED = "REQUEST_NOTIFICATION_PERMISSION_DENIED";

export const SEND_NOTIFICATION = "SEND_NOTIFICATION";
// MESSAGE ACTIONS
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";

export const LOAD_MY_MESSAGES = "LOAD_MY_MESSAGES";
export const LOAD_MY_MESSAGES_SUCCESS = "LOAD_MY_MESSAGES_SUCCESS";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";

// REGISTERATION ACTIONS
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

// RESET ACTIONS
export const STARTING_FORM = "STARTING_FORM";
export const RESET_FORM_SUCCESS = "RESET_FORM_SUCCESS";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
